stages: 
  - deploy

variables:
    DEPLOY_DIR: "/home/gitlab-runner/avahi-web" 

deploy-job:
  stage: deploy
  tags:
    - softlab
  environment: production
  script:
    - echo "Deploying application..."
    - rm -rf $DEPLOY_DIR
    - mkdir -p $DEPLOY_DIR
    - cp -a . $DEPLOY_DIR
    - python3 -m venv venv
    - cd $DEPLOY_DIR && source venv/bin/activate 
    - pip install -r requirements.txt
    - sudo systemctl restart avahi-web
    - echo "Application successfully deployed."
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "master"

